name: maupp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - fiona
  - geojson
  - geopandas
  - matplotlib
  - numpy
  - pandas
  - psycopg2
  - rasterio
  - scikit-learn
  - scipy
  - shapely
  - tqdm
  - imbalanced-learn
  - pip:
    - asarapi
    - pylandsat
    - sentinelsat
    - elevation